name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.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 }}
          assignees: "github.event.issue.user.login"
