name: Issue assignment

on:
  issues:
    types: [opened]
permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowSelfAssign: true
          assignees: "github.event.issue.user.login"
